name: spendwise
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^14.1.2
  hive_flutter: ^1.1.0
  hive_cache_manager: ^0.0.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  fl_chart: ^0.68.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  google_mlkit_text_recognition: ^0.13.0
  http: ^1.2.1
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  flutter_lints: ^4.0.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.13.1
  shimmer: ^3.0.0 
  excel: ^4.0.2


dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.1
  json_serializable: ^6.5.4
  hive_generator: ^2.0.1

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/colorsw.png"
  image_path_ios: "assets/images/whitesw.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#2A7C76"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
